### ISSUE TITLE
How would this work with the new version of React-Router (4)?

### ISSUE THREAD

**Issue by berlangerc** [JuliusKoronci/create-react-app-setup#1]
Making childs within a route doesn't seem to work.
How would this work with react-router v4?

Anyway: nice solution for router v3!

**Comment by JuliusKoronci** [comment]
Sorry this is just a testing app..I will update it..but it actually works with the child routes in v3..in v4 there are no child routes..and I am already using a different approach..I have a HOC which acts as a dependancy container (IoC) and I just register routes divided by categories..and render the router with the corresponding category where required

**Comment by JuliusKoronci** [comment]
Just to note..on the master branch you have the v4 version..on the v3 branch the v3
